spring:
  kafka:
    security:
      protocol: "PLAINTEXT"
    bootstrap-servers: localhost:9093
#    ssl:
#      trust-store-location: classpath:/client-certs/kafka.client.truststore.jks
#      trust-store-password: password
#      key-store-location:  classpath:/client-certs/kafka.client.keystore.jks
#      key-store-password: password
    consumer:
      group-id: demo-group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  bootstrapAddress: 172.29.52.194:9092

load:
  source:
    TestTopic: C:\_Develop\temp\kafka-util\src\main\resources\FilesForTopic

topic:
  create:
    - t1
    - t2
  delete:
    - q1
    - q2