spring:
  kafka:
    security:
      protocol: "PLAINTEXT"
#      protocol: "SSL"
    bootstrap-servers: localhost:9093
#    bootstrap-servers: localhost:29092,localhost:39092
#    bootstrap-servers: d5uasp-apc003lk.corp.dev.vtb:9092,d5uasp-apc003lk.corp.dev.vtb:9092,d5uasp-apc004lk.corp.dev.vtb:9092,d5uasp-apc018lk.corp.dev.vtb:9092,d5uasp-apc025lk.corp.dev.vtb:9092
    ssl:

      trust-store-password: kafkauasppassword
      key-store-password: kafkauasppassword
      key-password: kafkauasppassword
      key-store-location:  classpath:kafka-trust.pfx
      trust-store-location: classpath:APD00.13.01-USBP-kafka-cluster-uasp.pfx

    consumer:
      group-id: demo-group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
#  bootstrapAddress: 192.168.227.60:9092,192.168.227.60:9091
  bootstrapAddress: localhost:29092,localhost:39092

#load:
#  source:
#    filterTopic: C:\Work\temp\kafka-util\src\main\resources\FilesForTopic
#load:
#  source:
#    rate-topic: /home/vood/IdeaProjects/kafka-util/src/main/resources/rates

#    rate-topic: C:\Work\temp\kafka-util\src\main\resources\rates
#    main-topic: C:\Work\temp\kafka-util\src\main\resources\rateReq
#    rate_in_1: C:\Work\temp\kafka-util\src\main\resources\enrichRate
#    DEV.OUTER.CBR.RATES: C:\Work\temp\kafka-util\src\main\resources\enrichRate
topic:
  create:
    numPartitions: 3
    replicationFactor: 2
    names:
      - t1
      - t2
#  delete:
#    - q1
#    - q2