spring:
  kafka:
    security:
      protocol: "PLAINTEXT"
#    bootstrap-servers: localhost:9093
    bootstrap-servers: localhost:29092,localhost:39092
#    ssl:
#      trust-store-location: classpath:/client-certs/kafka.client.truststore.jks
#      trust-store-password: password
#      key-store-location:  classpath:/client-certs/kafka.client.keystore.jks
#      key-store-password: password
    consumer:
      group-id: demo-group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
#  bootstrapAddress: 192.168.227.60:9092,192.168.227.60:9091
  bootstrapAddress: localhost:29092,localhost:39092

#load:
#  source:
#    filterTopic: C:\Work\temp\kafka-util\src\main\resources\FilesForTopic
#load:
#  source:
#    rate-topic: /home/vood/IdeaProjects/kafka-util/src/main/resources/rates

#    rate-topic: C:\Work\temp\kafka-util\src\main\resources\rates
#    main-topic: C:\Work\temp\kafka-util\src\main\resources\rateReq
#    rate_in_1: C:\Work\temp\kafka-util\src\main\resources\enrichRate
#    DEV.OUTER.CBR.RATES: C:\Work\temp\kafka-util\src\main\resources\enrichRate
topic:
  create:
    numPartitions: 1
    replicationFactor: 1
    names:
      - t1
      - t2
#  delete:
#    - q1
#    - q2